### ISSUE TITLE
[Safe Apps Analytics] Relative share of transaction counts coming from Safe Apps

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-transaction-service#1164]
# Formula
total_transactions = count(Multisigtransactions)
total_safe_app_transactions = count(Multisigtransactions.filter(origin__contains=url)
percent = (total_transactions/total_safe_app_transactions)*100

# Response example
{
'total_tx' : '962076',
'total_safe_app_tx': 146360,
'percent': 15.2129
`timestamp': now
}

# Tasks
- [ ] Create a periodic task each 10 minutes to get the values
- [ ] Store the values in cache
- [ ] Create endpoint to return the values
