### ISSUE TITLE
[Safe Apps Analytics] Transactions count per Safe App

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-transaction-service#1165]
# Query
The following query is a generic idea of the query, it doesn't work on django orm:
`result = Multisigtransaction.filter(origin__contains='url').group_by(origin)`

# Result example:
The result is a list of Safe Apps and Custom Apps with the total count of transactions.
```
[
  {
    "url": "https://wry-graph.net",
    "name": "aperiam",
    "total-transactions": 56,
    "transactions-last-week": 51,
    "transactions-last-month": 14,
    "transactions-last-year": 79,
    "id": "1"
  },
  {
    "url": "https://smooth-feast.biz",
    "name": "quis",
    "total-transactions": 42,
    "transactions-last-week": 64,
    "transactions-last-month": 42,
    "transactions-last-year": 29,
    "id": "2"
  }
]
```

# Tasks
- [x] migrate origin from charField to JsonField
- [ ] create periodic task each 1 week to get the data from DB
- [x] store the data in cache
- [x] create an endpoint to return the result

# Comments
We should check that the same origin is grouped only one time, avoiding repeated origins, for example because the parameter order:
```
{'origin': '{"url":"https://app.uniswap.org/","name":"Uniswap"}'
{'origin': '{"name":"Uniswap", "url":"https://app.uniswap.org/"}'
```
