### ISSUE TITLE
[Safe Apps Analytics] Safe signatures signing safe apps transactions

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-transaction-service#1167]
# Formula
total_signatures = count(mutltisigconfirmations)
total_signatures_safe_apps = count(multisigconfirmations__multisigtransactions__where__origin__contains__url)
(total_signatures_safe_apps / total_signatures ) * 100

# Response
{
'total_signatures': integer,
'total_signatures_safe_apps': integer,
'percent': float
}

# Tasks
- [ ] Create a periodic task each 10 minutes to get the values
- [ ] Store the values in cache
- [ ] Create endpoint to return the values
